USE BD_ANAC

/*1) QUAIS OS 3 AEROPORTOS DE ORIGEM QUE TIVERAM O MAIOR PERCENTUAL DE VOOS DOMESTICOS REALIZADOS? CONSIDERE OS AERODROMOS
COM MAIS DE 10000 VOOS DOMESTICOS */
SELECT TOP 3
    TB_AERODROMO.NM_AERODROMO,
    TB_TIPO_LINHA.DS_NATUREZA_TIPO_LINHA,
    COUNT(TB_VOO.DT_HR_PARTIDA_PREVISTA)    QT_VOOS_PREVISTOS,
    COUNT(TB_VOO.DT_HR_CHEGADA_REAL)        QT_VOOS_REALIZADOS,
    ((COUNT(TB_VOO.DT_HR_CHEGADA_REAL) * 100) / COUNT(TB_VOO.DT_HR_PARTIDA_PREVISTA)) PORCENTAGEM
FROM TB_VOO
    INNER JOIN TB_TIPO_LINHA
            ON TB_TIPO_LINHA.ID = TB_VOO.ID_TIPO_LINHA
    INNER JOIN TB_AERODROMO
            ON TB_AERODROMO.ID = TB_VOO.ID_AERODROMO_ORIGEM 
WHERE TB_TIPO_LINHA.ID IN (1,4)
GROUP BY NM_AERODROMO, TB_TIPO_LINHA.DS_NATUREZA_TIPO_LINHA
    HAVING COUNT(TB_VOO.DT_HR_CHEGADA_REAL) > 10000
ORDER BY PORCENTAGEM DESC

/*2) QUAL A DURACAO REAL MEDIA (EM MINUTOS) DOS VOOS REALIZADOS ENTRE O ESTADO DE SP (ORIGEM) E BUENOS AIRES (DESTINO) ? */
SELECT 
    --TB_AERODROMO.SG_UF ORIGEM,
    --TB_VOO.ID_AERODROMO_DESTINO DESTINO,
    --TB_VOO.DT_HR_PARTIDA_REAL PARTIDA,
    --TB_VOO.DT_HR_CHEGADA_REAL CHEGADA,
    AVG(DATEDIFF(MI, TB_VOO.DT_HR_PARTIDA_REAL, TB_VOO.DT_HR_CHEGADA_REAL)) OVER() MEDIA  
FROM TB_VOO
    INNER JOIN TB_AERODROMO
            ON TB_AERODROMO.ID = TB_VOO.ID_AERODROMO_ORIGEM     
WHERE TB_AERODROMO.SG_UF = 'SP'
AND   TB_VOO.ID_AERODROMO_DESTINO = 295
AND   TB_VOO.DT_HR_PARTIDA_REAL IS NOT NULL
GROUP BY TB_AERODROMO.SG_UF, TB_VOO.ID_AERODROMO_DESTINO, TB_VOO.DT_HR_PARTIDA_REAL, TB_VOO.DT_HR_CHEGADA_REAL

/*3) QUAL A EMPRESA ESTRANGEIRA COM A MAIOR QUANTIDADE DE VOOS, QUE SO ATUOU COM VOOS COM SERVICO DE TIPO DE LINHA CARGUEIRA? */
SELECT TOP 1
    TB_EMPRESA.NM_EMPRESA,
    --TB_EMPRESA.DS_TIPO_EMPRESA,
    --TB_TIPO_LINHA.DS_SERVICO_TIPO_LINHA,
    COUNT(*) MAIOR_NUM_VOO
    --MAX(COUNT(TB_VOO.ID_EMPRESA)) OVER(ORDER BY NM_EMPRESA) MAIOR_NUM_VOO
FROM TB_VOO
    INNER JOIN TB_EMPRESA
            ON TB_EMPRESA.ID = TB_VOO.ID_EMPRESA
    INNER JOIN TB_TIPO_LINHA
            ON TB_TIPO_LINHA.ID = TB_VOO.ID_TIPO_LINHA
WHERE DS_TIPO_EMPRESA       = 'ESTRANGEIRA'
AND   DS_SERVICO_TIPO_LINHA = 'CARGUEIRA'
GROUP BY    TB_EMPRESA.NM_EMPRESA
          --TB_EMPRESA.DS_TIPO_EMPRESA,
          --TB_TIPO_LINHA.DS_SERVICO_TIPO_LINHA
ORDER BY MAIOR_NUM_VOO DESC

/*4) QUAL A EMPRESA QUE POSSUI MAIOR MEDIA DE ATRASADO NA PARTIDA? */
SELECT TOP 1
    NM_EMPRESA,
    --DT_HR_PARTIDA_PREVISTA,
    --DT_HR_PARTIDA_REAL,
    AVG(DATEDIFF(MI, DT_HR_PARTIDA_PREVISTA, DT_HR_PARTIDA_REAL))  MEDIA_ATRASO
FROM TB_VOO
    INNER JOIN TB_EMPRESA
            ON TB_EMPRESA.ID = TB_VOO.ID_EMPRESA
WHERE DATEDIFF(MI, DT_HR_PARTIDA_PREVISTA, DT_HR_PARTIDA_REAL) > 0
GROUP BY NM_EMPRESA
ORDER BY MEDIA_ATRASO DESC

/*5) QUAL O AEROPORTO (DE ORIGEM) QUE TEVE O MAIOR PERCENTUAL DE VOOS, REGULARES, CANCELADOS? CONSIDERE APENAS OS COM MAIS DE 
5000 VOOS */
SELECT TOP 1
    NM_AERODROMO,
    DS_TIPO_VOO,
    ((COUNT(DT_HR_PARTIDA_REAL) * 100) / COUNT(DT_HR_PARTIDA_PREVISTA)) PORCENTAGEM
FROM TB_VOO
    INNER JOIN TB_TIPO_VOO
            ON TB_TIPO_VOO.ID = TB_VOO.ID_TIPO_VOO
    INNER JOIN TB_AERODROMO
            ON TB_AERODROMO.ID = TB_VOO.ID_AERODROMO_ORIGEM
WHERE DS_TIPO_VOO = 'REGULAR'
GROUP BY NM_AERODROMO, DS_TIPO_VOO
  HAVING COUNT(DT_HR_PARTIDA_PREVISTA) > 5000 
ORDER BY PORCENTAGEM DESC

/*6) QUAL A DURACAO REAL MEDIA (EM MINUTOS) DE VOOS REALIZADOS ENTRE A CIDADE DE SAO PAULO (ORIGEM) E A CIDADE 
DO RIO DE JANEIRO (DESTINO)? */
SELECT
    --ID_AERODROMO_ORIGEM,
    --ID_AERODROMO_DESTINO,
    --DT_HR_PARTIDA_REAL,
    --DT_HR_CHEGADA_REAL,
    AVG(DATEDIFF(MI, DT_HR_PARTIDA_REAL, DT_HR_CHEGADA_REAL)) DUR_MED_VOOS
FROM TB_VOO
WHERE ID_AERODROMO_ORIGEM IN (SELECT
                                ID
                            FROM TB_AERODROMO
                            WHERE NM_CIDADE = 'SÃO PAULO' 
                            )
AND ID_AERODROMO_DESTINO IN (SELECT
                                ID
                            FROM TB_AERODROMO
                            WHERE NM_CIDADE = 'RIO DE JANEIRO' 
                            )

/*7) QUAL A EMPRESA BRASILEIRA COM A MAIOR QUANTIDADE DE VOOS MISTA? */
SELECT DISTINCT TOP 1
   NM_EMPRESA,
   COUNT(ID_VOO) OVER (ORDER BY NM_EMPRESA) CONT_VOOS
FROM TB_VOO
    INNER JOIN TB_TIPO_LINHA
            ON TB_TIPO_LINHA.ID = TB_VOO.ID_TIPO_LINHA
    INNER JOIN TB_EMPRESA
            ON TB_EMPRESA.ID = TB_VOO.ID_EMPRESA
WHERE TB_TIPO_LINHA.CD_TIPO_LINHA IN ('N','I') 
AND TB_EMPRESA.DS_TIPO_EMPRESA = 'BRASILEIRA'
ORDER BY CONT_VOOS DESC

/*8) QUAL EMPRESA POSSUI A MAIOR MEDIA DE ATRASADO NA CHEGADA? */
SELECT TOP 1
    NM_EMPRESA,
    --DT_HR_CHEGADA_PREVISTA,
    --DT_HR_CHEGADA_REAL,
    AVG(DATEDIFF(MI,DT_HR_CHEGADA_PREVISTA,DT_HR_CHEGADA_REAL))  MEDIA_ATRASO
FROM TB_VOO
    INNER JOIN TB_EMPRESA
            ON TB_EMPRESA.ID = TB_VOO.ID_EMPRESA
WHERE DT_HR_CHEGADA_REAL > DT_HR_CHEGADA_PREVISTA
GROUP BY TB_EMPRESA.ID, NM_EMPRESA
ORDER BY MEDIA_ATRASO DESC

/*9) QUAIS AS 4 EMPRESAS QUE TIVERAM O MAIOR PERCENTUAL DE VOOS INTERNACIONAIS REALIZADOS? CONSIDERE APENAS AS EMPRESAS COM MAIS 
DE 1000 VOOS INTERNACIONAIS.*/
SELECT TOP 4 
    NM_EMPRESA,
    --DS_NATUREZA_TIPO_LINHA,
    --DT_HR_PARTIDA_PREVISTA,
    --DT_HR_PARTIDA_REAL,
    ((COUNT(DT_HR_PARTIDA_REAL) * 100) / COUNT(DT_HR_PARTIDA_PREVISTA)) CONTAGEM
FROM TB_VOO
    INNER JOIN TB_EMPRESA
            ON TB_EMPRESA.ID = TB_VOO.ID_EMPRESA
    INNER JOIN TB_TIPO_LINHA
            ON TB_TIPO_LINHA.ID = TB_VOO.ID_TIPO_LINHA
WHERE DS_NATUREZA_TIPO_LINHA = 'INTERNACIONAL'
--AND DATEDIFF(MI, DT_HR_PARTIDA_PREVISTA, DT_HR_PARTIDA_REAL) > 0
--AND   DT_HR_CHEGADA_REAL IS NOT NULL
GROUP BY NM_EMPRESA
         --DT_HR_PARTIDA_REAL,
         --DT_HR_PARTIDA_PREVISTA
HAVING COUNT(DT_HR_PARTIDA_PREVISTA) > 1000
ORDER BY CONTAGEM DESC


/*10) QUAL A DURAÇÃO PREVISTA MEDIA(EM MINUTOS) DOS VOOS REALIZADOS ENTRE O ESTADO DE SAO PAULO(ORIGEM) E SANTIAGO(DESTINO) NO CHILE? */
SELECT
    AVG(DATEDIFF(MI,DT_HR_PARTIDA_PREVISTA,DT_HR_CHEGADA_PREVISTA)) MEDIA
FROM TB_VOO
    INNER JOIN TB_AERODROMO ORIGEM
            ON ORIGEM.ID = TB_VOO.ID_AERODROMO_ORIGEM
    INNER JOIN TB_AERODROMO DESTINO 
            ON DESTINO.ID = TB_VOO.ID_AERODROMO_DESTINO
WHERE   ORIGEM.SG_UF = 'SP'
AND     DESTINO.NM_CIDADE = 'SANTIAGO DO CHILE'

/*11) QUAL O AEROPORTO DE ORIGEM NO BRASIL COM A MAIOR QUANTIDADE DE VOOS, QUE SÓ ATUOU COM VOOS MISTOS */
SELECT TOP 1
    NM_AERODROMO,
    COUNT(ID_AERODROMO_ORIGEM) QT_VOOS 
FROM TB_VOO
    INNER JOIN TB_AERODROMO
            ON TB_AERODROMO.ID = TB_VOO.ID_AERODROMO_ORIGEM
    INNER JOIN TB_TIPO_LINHA
            ON TB_TIPO_LINHA.ID = TB_VOO.ID_TIPO_LINHA
WHERE DS_SERVICO_TIPO_LINHA = 'MISTA'
AND   NM_PAIS = 'BRASIL'
GROUP BY NM_AERODROMO
ORDER BY QT_VOOS DESC

/*12) QUAL AEROPORTO DE ORIGEM QUE POSSUI A MAIOR MEDIA DE ATRASADO NA PARTIDA? */
SELECT 
    NM_AERODROMO,
    AVG(DATEDIFF(MI,DT_HR_PARTIDA_PREVISTA,DT_HR_PARTIDA_REAL)) MEDIA_ATRASO
FROM TB_VOO
    INNER JOIN TB_AERODROMO
            ON TB_AERODROMO.ID = TB_VOO.ID_AERODROMO_ORIGEM
WHERE DT_HR_PARTIDA_REAL > DT_HR_PARTIDA_PREVISTA
GROUP BY NM_AERODROMO
ORDER BY MEDIA_ATRASO DESC

